---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: user-deploy
spec:
  selector:
    matchLabels:
      app: user-deploy
  replicas: 1
  template:
    metadata:
      labels:
        app: user-deploy
    spec:
      containers:
      - name: user-container
        image: devkwetter.azurecr.io/user-image
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          value: http://*:8080