name: Update Database & Dependency Checker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Update database
      working-directory: src/kwetter_be_user
      run: |
        dotnet tool install --global dotnet-ef
        dotnet tool restore
        dotnet ef database update
      env:
        ASPNETCORE_ENVIRONMENT: Development
    - name: Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      id: Depcheck
      with:
        project: 'test'
        path: '.'
        format: 'HTML'
