name: Kubernetes YAML scan

on: [push, pull_request]
jobs:
  kubescape:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@master
    - name: Install kubescape
      run: curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | /bin/bash
    - name: Scan repository
      working-directory: src/kwetter_be_user
      run: kubescape scan deployment.yaml
